# Generated by Django 6.0.2 on 2026-02-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0004_chatgroup_is_private_chatgroup_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
