# Generated by Django 6.0.2 on 2026-02-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0005_alter_chatgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='groupchat_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
