# Generated by Django 6.0.2 on 2026-02-20 18:57

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0006_chatgroup_groupchat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=255, unique=True),
        ),
    ]
