# Generated by Django 6.0.2 on 2026-02-20 19:16

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0008_alter_chatgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='groupchat_name',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=255, unique=True),
        ),
    ]
